# Generated by Django 4.0.4 on 2022-07-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('date_published', models.DateTimeField()),
            ],
        ),
    ]
