# Generated by Django 4.0.4 on 2022-07-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyArticle',
            new_name='Article',
        ),
    ]
