# Generated by Django 4.0.4 on 2022-07-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_content',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
    ]
