# Generated by Django 4.0.4 on 2022-07-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0004_article_short_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_heading',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
