# Generated by Django 4.0.4 on 2022-07-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0005_article_is_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_heading',
            new_name='is_headline',
        ),
    ]
